package ui

import (
	"html/template"
	"strings"
)

func Escape(value string) string { return template.HTMLEscapeString(value) }

const baseStyles = `
:root{color-scheme:dark;--bg:#090a0d;--panel:#12161b;--soft:#1a2028;--text:#f5f7fa;--muted:#9aa4b2;--line:#29313c;--accent:#2997ff;--danger:#ff6b6b;--green:#50d890;--shadow:0 24px 70px rgba(0,0,0,.32)}
*{box-sizing:border-box}html,body{max-width:100%;overflow-x:hidden}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 -apple-system,BlinkMacSystemFont,"SF Pro Text","Segoe UI",sans-serif}a{color:inherit}.shell{max-width:1040px;margin:0 auto;padding:64px 20px}.brand{display:flex;align-items:center;gap:10px;font-weight:800;margin-bottom:32px}.dot{width:11px;height:11px;border-radius:50%;background:#52d273;box-shadow:0 0 18px #52d27366}.card{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:28px;box-shadow:0 20px 60px #0005}h1{margin:0 0 8px;font-size:30px;line-height:1.2}.sub{color:var(--muted);margin-bottom:24px}.form{display:grid;gap:14px}.field{display:grid;gap:6px}.input{width:100%;padding:12px 13px;border:1px solid var(--line);border-radius:10px;background:var(--soft);color:var(--text);font:inherit}.btn{display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:11px 15px;border-radius:10px;border:1px solid var(--line);background:var(--soft);color:var(--text);text-decoration:none;font-weight:700;cursor:pointer}.btn.primary{background:var(--accent);border-color:var(--accent);color:#07111f}.hint,.row-meta{color:var(--muted);font-size:13px}.alert{padding:11px 13px;border:1px solid #ff6b6b66;background:#ff6b6b14;color:#ffb3b3;border-radius:10px}.auth-switch{margin-top:18px;color:var(--muted)}.stack{display:grid;gap:12px}.row{padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--soft)}.row-title{font-weight:700}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-all}.actions{display:flex;gap:10px;flex-wrap:wrap}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.metric-box{padding:16px;border:1px solid var(--line);border-radius:12px;background:var(--soft)}.metric-label{color:var(--muted);font-size:12px}.metric-value{font-size:28px;font-weight:800;margin-top:4px}.badge{display:inline-flex;align-items:center;padding:3px 8px;border-radius:999px;border:1px solid var(--line);font-size:11px;font-weight:700;vertical-align:middle}.badge.green{color:#7be0a8;border-color:#2e6f4a;background:#173323}.badge.blue{color:#9fc5ff;border-color:#315a8b;background:#17283c}.badge.muted{color:var(--muted);background:#15191f}.tree{display:grid;gap:8px;margin-top:12px}.tree-node{position:relative;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--soft)}.tree-node:before{content:"";position:absolute;left:-12px;top:50%;width:10px;border-top:1px solid var(--line)}
@media(max-width:720px){.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.tree-node{margin-left:0!important}}@media(max-width:520px){.shell{padding:28px 14px}.card{padding:20px}h1{font-size:26px}.metrics{grid-template-columns:1fr}}
`

const dashboardStyles = `
:root{--dash-bg:#090a0d;--dash-surface:rgba(24,26,32,.78);--dash-surface2:rgba(27,29,36,.66);--dash-surface3:rgba(34,37,45,.84);--dash-line:rgba(255,255,255,.105);--dash-line-soft:rgba(255,255,255,.062);--dash-text:#f5f5f7;--dash-muted:#a1a1a6;--dash-muted2:#77777d;--dash-accent:#2997ff;--dash-green:#4ad969;--dash-red:#ff453a;--dash-shadow:0 28px 80px rgba(0,0,0,.3),0 2px 12px rgba(0,0,0,.22)}
body.dashboard{min-height:100vh;color:var(--dash-text);background:radial-gradient(900px 560px at 78% -15%,rgba(0,113,227,.14),transparent 62%),radial-gradient(720px 520px at 28% 110%,rgba(110,92,255,.1),transparent 66%),var(--dash-bg)}
.dash-shell{min-height:100vh;display:grid;grid-template-columns:264px minmax(0,1fr)}.dash-sidebar{position:sticky;top:0;height:100vh;padding:20px 16px 16px;border-right:1px solid var(--dash-line-soft);background:rgba(13,14,18,.76);backdrop-filter:saturate(180%) blur(32px);display:flex;flex-direction:column}.dash-brand{display:flex;align-items:center;gap:12px;padding:3px 8px 24px}.dash-logo{width:38px;height:38px;border-radius:12px;background:#0b1020;box-shadow:0 10px 28px rgba(30,64,175,.18)}.dash-brand-name{font-size:16px;font-weight:760;letter-spacing:-.025em}.dash-brand-tag{margin-left:auto;border:0;background:rgba(0,113,227,.09);color:var(--dash-accent);font-size:9px;font-weight:750;letter-spacing:.11em;padding:5px 8px;border-radius:999px}.dash-nav-label{padding:9px 12px 8px;color:var(--dash-muted2);font-size:10px;font-weight:680;letter-spacing:.1em;text-transform:uppercase}.dash-nav{display:grid;gap:5px}.dash-nav a{display:flex;align-items:center;gap:11px;min-height:42px;padding:10px 12px;border-radius:13px;color:var(--dash-muted);font-size:13px;font-weight:560;text-decoration:none;transition:.18s ease}.dash-nav a:hover{background:rgba(127,127,127,.08);color:var(--dash-text);transform:translateX(1px)}.dash-nav a.active{background:rgba(0,113,227,.1);box-shadow:inset 0 0 0 .5px rgba(0,113,227,.14);color:var(--dash-accent)}.dash-nav-icon{width:20px;height:20px;display:grid;place-items:center}.dash-nav-icon svg{width:19px;height:19px;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}.dash-spacer{flex:1}.dash-status{margin:16px 6px;padding:14px;border:1px solid var(--dash-line-soft);border-radius:17px;background:var(--dash-surface2)}.dash-status-title{display:flex;align-items:center;gap:8px;font-size:11px;font-weight:650}.dash-status-copy{color:var(--dash-muted2);font-size:10.5px;line-height:1.55;margin-top:6px}.dash-status-dot{width:7px;height:7px;border-radius:50%;background:var(--dash-green);box-shadow:0 0 0 4px rgba(74,217,105,.09),0 0 16px rgba(74,217,105,.24)}.dash-foot{padding:14px 6px 1px;border-top:1px solid var(--dash-line-soft)}.dash-foot .btn{width:100%;min-height:36px;padding:8px 12px;border-radius:11px;background:var(--dash-surface3);border-color:var(--dash-line);font-size:11px;color:var(--dash-text)}
.dash-main{min-width:0;width:100%;max-width:1380px;margin:0 auto;padding:50px 52px 76px}.dash-top{margin-bottom:30px}.dash-eyebrow{display:flex;align-items:center;gap:8px;color:var(--dash-muted2);font-size:10px;font-weight:680;letter-spacing:.11em;text-transform:uppercase}.dash-eyebrow:before{content:"";width:8px;height:8px;border-radius:50%;background:var(--dash-green);box-shadow:0 0 12px rgba(74,217,105,.35)}.dash-title{font-size:38px;font-weight:720;letter-spacing:-.045em;line-height:1.08;margin:9px 0 7px}.dash-sub{max-width:820px;color:var(--dash-muted);font-size:14px;line-height:1.58}.page-body{min-width:0}.page-body>.actions:first-child{display:none}.page-body>.stack{gap:12px}
.dashboard .metrics{gap:18px}.dashboard .metric-box{min-height:126px;padding:22px 24px;border:1px solid var(--dash-line);border-radius:20px;background:var(--dash-surface);box-shadow:var(--dash-shadow)}.dashboard .metric-label{padding-top:8px;color:var(--dash-muted);font-size:11px;font-weight:620}.dashboard .metric-value{font-size:38px;font-weight:700;letter-spacing:-.05em;margin-top:11px;line-height:1}.dashboard .row{padding:15px 18px;border:1px solid var(--dash-line);border-radius:16px;background:var(--dash-surface);box-shadow:0 10px 36px rgba(0,0,0,.12)}.dashboard .row-title{font-size:13px;font-weight:650;letter-spacing:-.012em}.dashboard .row-meta{color:var(--dash-muted2);font-size:10.5px;line-height:1.55;margin-top:4px}.dashboard .stack{display:grid;gap:10px}.dashboard .badge{border-color:transparent;border-radius:999px;padding:5px 9px;font-size:9.5px;font-weight:650}.dashboard .badge.green{color:var(--dash-green);background:rgba(74,217,105,.1)}.dashboard .badge.blue{color:var(--dash-accent);background:rgba(41,151,255,.1)}.dashboard .badge.muted{color:var(--dash-muted);background:rgba(127,127,127,.09)}.dashboard .tree{gap:9px}.dashboard .tree-node{padding:12px 14px;border:1px solid var(--dash-line);border-radius:14px;background:var(--dash-surface2)}
@media(max-width:900px){.dash-shell{grid-template-columns:220px minmax(0,1fr)}.dash-main{padding:38px 28px 60px}}@media(max-width:760px){.dash-shell{display:block}.dash-sidebar{position:relative;height:auto;border-right:0;border-bottom:1px solid var(--dash-line-soft);padding:12px}.dash-brand{padding:3px 6px 11px}.dash-nav-label,.dash-status,.dash-foot{display:none}.dash-nav{display:flex;overflow-x:auto;gap:5px}.dash-nav a{white-space:nowrap;flex:0 0 auto;padding:8px 10px}.dash-main{padding:24px 15px 46px}.dash-title{font-size:29px}.dashboard .metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:520px){.dashboard .metrics{grid-template-columns:1fr}}
`

func icon(path string) string {
	return `<svg viewBox="0 0 24 24" aria-hidden="true">` + path + `</svg>`
}

func dashboardPage(title, subtitle, body string) string {
	brand := `<div class="dash-brand"><img class="dash-logo" src="/assets/codelocal-icon.png" alt=""><span class="dash-brand-name">CodeLocal</span><span class="dash-brand-tag">CLOUD</span></div>`
	nav := `<div class="dash-nav-label">Control plane</div><nav class="dash-nav" id="dashboard-nav">` +
		`<a href="/dashboard" data-route="/dashboard"><span class="dash-nav-icon">` + icon(`<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>`) + `</span>Overview</a>` +
		`<a href="/dashboard/workspaces" data-route="/dashboard/workspaces"><span class="dash-nav-icon">` + icon(`<path d="M3.5 7.5h6l2-2h9v13.5H3.5z"/><path d="M3.5 9.5h17"/>`) + `</span>Workspaces</a>` +
		`<a href="/dashboard/devices" data-route="/dashboard/devices"><span class="dash-nav-icon">` + icon(`<rect x="5" y="3" width="14" height="18" rx="3"/><path d="M9.5 6h5M11 18h2"/>`) + `</span>Devices</a>` +
		`<a href="/dashboard/usage" data-route="/dashboard/usage"><span class="dash-nav-icon">` + icon(`<path d="M4 18V9M10 18V5M16 18v-7M22 18V3"/>`) + `</span>Token usage</a>` +
		`<a href="/#setup"><span class="dash-nav-icon">` + icon(`<path d="M8 12h8M13 9l3 3-3 3"/><path d="M5 5.5h6M5 18.5h6"/>`) + `</span>Connect ChatGPT</a>` +
		`</nav>`
	status := `<div class="dash-spacer"></div><div class="dash-status"><div class="dash-status-title"><span class="dash-status-dot"></span>Cloud connected</div><div class="dash-status-copy">Local source code and secrets stay on your machine.</div></div><div class="dash-foot" id="dashboard-foot"></div>`
	script := `<script>(()=>{const path=location.pathname;document.querySelectorAll('[data-route]').forEach(a=>{const route=a.getAttribute('data-route');if(path===route)a.classList.add('active')});const legacy=document.querySelector('.page-body > .actions');if(legacy){const admin=legacy.querySelector('a[href="/dashboard/admin"]');if(admin){const copy=admin.cloneNode(true);copy.className='';copy.innerHTML='<span class="dash-nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v5c0 4.6-2.8 8.3-7 10-4.2-1.7-7-5.4-7-10V6z"/><path d="M9.5 12l1.7 1.7 3.5-4"/></svg></span>Admin';copy.dataset.route='/dashboard/admin';document.getElementById('dashboard-nav')?.appendChild(copy);if(path==='/dashboard/admin')copy.classList.add('active')}const form=legacy.querySelector('form[action="/logout"]');if(form){document.getElementById('dashboard-foot')?.appendChild(form)}legacy.remove()}})();</script>`
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><link rel="icon" href="/favicon.ico"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><title>` + Escape(title) + ` · CodeLocal</title><style>` + baseStyles + dashboardStyles + `</style></head><body class="dashboard"><div class="dash-shell"><aside class="dash-sidebar">` + brand + nav + status + `</aside><main class="dash-main"><header class="dash-top"><div class="dash-eyebrow">CodeLocal Cloud</div><h1 class="dash-title">` + Escape(title) + `</h1><div class="dash-sub">` + Escape(subtitle) + `</div></header><div class="page-body">` + body + `</div></main></div>` + script + `</body></html>`
}

func Page(title, subtitle, body string) string {
	if strings.Contains(title, "CodeLocal Cloud") {
		return dashboardPage(title, subtitle, body)
	}
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>` + Escape(title) + ` · CodeLocal</title><style>` + baseStyles + `</style></head><body><main class="shell"><div class="brand"><span class="dot"></span>CodeLocal</div><section class="card"><h1>` + Escape(title) + `</h1><div class="sub">` + Escape(subtitle) + `</div>` + body + `</section></main></body></html>`
}

func Hidden(fields map[string]string) string {
	var out strings.Builder
	for key, value := range fields {
		out.WriteString(`<input type="hidden" name="` + Escape(key) + `" value="` + Escape(value) + `">`)
	}
	return out.String()
}
