package ui

import (
	"html/template"
	"strings"
)

func Escape(value string) string { return template.HTMLEscapeString(value) }

const baseStyles = `
:root{color-scheme:dark;--bg:#090a0d;--panel:#12161b;--soft:#1a2028;--text:#f5f7fa;--muted:#9aa4b2;--line:#29313c;--accent:#8b7cff;--accent2:#5ca9ff;--danger:#ff6978;--green:#50d890;--shadow:0 24px 70px rgba(0,0,0,.32)}
*{box-sizing:border-box}html,body{max-width:100%;overflow-x:hidden}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}a{color:inherit}.shell{max-width:1040px;margin:0 auto;padding:64px 20px}.brand{display:flex;align-items:center;gap:10px;font-weight:800;margin-bottom:32px}.dot{width:11px;height:11px;border-radius:50%;background:#52d273;box-shadow:0 0 18px #52d27366}.card{background:var(--panel);border:1px solid var(--line);border-radius:18px;padding:28px;box-shadow:0 20px 60px #0005}h1{margin:0 0 8px;font-size:30px;line-height:1.2}.sub{color:var(--muted);margin-bottom:24px}.form{display:grid;gap:14px}.field{display:grid;gap:6px}.input{width:100%;padding:12px 13px;border:1px solid var(--line);border-radius:10px;background:var(--soft);color:var(--text);font:inherit}.btn{display:inline-flex;justify-content:center;align-items:center;gap:8px;padding:10px 13px;border-radius:10px;border:1px solid var(--line);background:var(--soft);color:var(--text);text-decoration:none;font-weight:700;cursor:pointer}.btn.primary{border-color:transparent;background:linear-gradient(135deg,var(--accent),var(--accent2));color:#fff}.hint,.row-meta{color:var(--muted);font-size:13px}.alert{padding:11px 13px;border:1px solid #ff6b6b66;background:#ff6b6b14;color:#ffb3b3;border-radius:10px}.auth-switch{margin-top:18px;color:var(--muted)}.stack{display:grid;gap:12px}.row{padding:14px;border:1px solid var(--line);border-radius:12px;background:var(--soft)}.row-title{font-weight:700}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;word-break:break-word}.actions{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.metric-box{padding:16px;border:1px solid var(--line);border-radius:12px;background:var(--soft)}.metric-label{color:var(--muted);font-size:12px}.metric-value{font-size:28px;font-weight:800;margin-top:4px}.badge{display:inline-flex;align-items:center;padding:3px 8px;border-radius:999px;border:1px solid var(--line);font-size:11px;font-weight:700;vertical-align:middle}.badge.green{color:#7be0a8;border-color:#2e6f4a;background:#173323}.badge.blue{color:#a9b8ff;border-color:#514b8d;background:#211e3e}.badge.muted{color:var(--muted);background:#15191f}.tree{display:grid;gap:8px;margin-top:12px}.tree-node{position:relative;padding:10px 12px;border:1px solid var(--line);border-radius:10px;background:var(--soft)}.tree-node:before{content:"";position:absolute;left:-12px;top:50%;width:10px;border-top:1px solid var(--line)}
@media(max-width:720px){.metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.tree-node{margin-left:0!important}}@media(max-width:520px){.shell{padding:28px 14px}.card{padding:20px}h1{font-size:26px}.metrics{grid-template-columns:1fr}}
`

const dashboardStyles = `
:root{--dash-bg:#090a0d;--dash-bg2:#0d0f13;--dash-surface:#11141a;--dash-surface2:#161a21;--dash-surface3:#1b2029;--dash-line:#242a35;--dash-line-soft:#1c212a;--dash-text:#f7f8fb;--dash-muted:#929bad;--dash-muted2:#6f7889;--dash-accent:#8b7cff;--dash-accent2:#5ca9ff;--dash-green:#50d890;--dash-red:#ff6978;--dash-shadow:0 24px 70px rgba(0,0,0,.32)}
body.dashboard{min-height:100vh;color:var(--dash-text);background:radial-gradient(900px 520px at 8% -14%,rgba(139,124,255,.16),transparent 60%),radial-gradient(760px 500px at 100% 8%,rgba(92,169,255,.08),transparent 62%),var(--dash-bg)}
.dash-shell{min-height:100vh;width:100%;display:grid;grid-template-columns:248px minmax(0,1fr)}.dash-sidebar{position:sticky;top:0;height:100vh;min-width:0;padding:20px 14px;border-right:1px solid var(--dash-line-soft);background:rgba(9,10,13,.84);backdrop-filter:blur(24px);display:flex;flex-direction:column}.dash-brand{display:flex;align-items:center;gap:11px;padding:5px 8px 21px}.dash-logo{width:31px;height:31px;flex:0 0 31px;border-radius:10px;background:#0b1020;box-shadow:0 10px 28px rgba(112,126,255,.25)}.dash-brand-name{font-size:15px;font-weight:780;letter-spacing:-.025em}.dash-brand-tag{margin-left:auto;border:1px solid var(--dash-line);background:var(--dash-surface);color:var(--dash-muted);font-size:9px;font-weight:800;letter-spacing:.08em;padding:4px 6px;border-radius:999px}.dash-nav-label{padding:10px 10px 6px;color:var(--dash-muted2);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.dash-nav{display:grid;gap:3px}.dash-nav a{display:flex;align-items:center;gap:10px;padding:9px 10px;border-radius:10px;color:var(--dash-muted);font-size:13px;font-weight:600;text-decoration:none;transition:.15s ease}.dash-nav a:hover{background:rgba(255,255,255,.035);color:var(--dash-text)}.dash-nav a.active{background:linear-gradient(90deg,rgba(139,124,255,.13),rgba(92,169,255,.06));box-shadow:inset 0 0 0 1px rgba(139,124,255,.13);color:#fff}.dash-nav a.active .dash-nav-icon{color:#b8afff}.dash-nav-icon{width:19px;height:19px;display:grid;place-items:center}.dash-nav-icon svg{width:19px;height:19px;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}.dash-spacer{flex:1}.dash-status{margin:14px 7px;padding:12px;border:1px solid var(--dash-line-soft);border-radius:12px;background:rgba(17,20,26,.72)}.dash-status-title{display:flex;align-items:center;gap:8px;font-size:11px;font-weight:700}.dash-status-copy{color:var(--dash-muted2);font-size:10px;margin-top:5px;line-height:1.45}.dash-status-dot{width:7px;height:7px;border-radius:50%;background:var(--dash-green);box-shadow:0 0 0 3px rgba(80,216,144,.09),0 0 14px rgba(80,216,144,.2)}.dash-foot{padding:12px 8px 2px;border-top:1px solid var(--dash-line-soft)}.dash-account{display:flex;align-items:center;gap:9px;margin-bottom:10px}.dash-avatar{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;background:var(--dash-surface3);border:1px solid var(--dash-line);font-size:11px;font-weight:800}.dash-account-copy{min-width:0}.dash-account-email{max-width:155px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px;font-weight:650}.dash-account-meta{font-size:10px;color:var(--dash-muted2)}.dash-foot .btn{width:100%;min-height:34px;padding:7px 10px;border-radius:10px;background:var(--dash-surface3);border-color:var(--dash-line);font-size:10.5px;color:var(--dash-text)}
.dash-main{min-width:0;width:100%;max-width:1320px;margin:0 auto;padding:38px 44px 64px}.dash-top{display:flex;justify-content:space-between;align-items:flex-start;gap:22px;margin-bottom:28px}.dash-eyebrow{display:flex;align-items:center;gap:7px;color:var(--dash-muted2);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.13em}.dash-eyebrow:before{content:"";width:7px;height:7px;border-radius:50%;background:var(--dash-green);box-shadow:0 0 14px rgba(80,216,144,.25)}.dash-title{font-size:31px;font-weight:790;letter-spacing:-.04em;line-height:1.12;margin:7px 0 4px}.dash-sub{max-width:760px;color:var(--dash-muted);font-size:13px;line-height:1.6}.page-body{min-width:0}.page-body>[data-dashboard-email]{display:none}
.dashboard .grid{min-width:0;display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:15px}.dashboard .span3{grid-column:span 3}.dashboard .span4{grid-column:span 4}.dashboard .span6{grid-column:span 6}.dashboard .span8{grid-column:span 8}.dashboard .span12{grid-column:span 12}.dashboard .card{min-width:0;border:1px solid var(--dash-line);border-radius:16px;background:linear-gradient(180deg,rgba(20,24,31,.95),rgba(15,18,23,.96));box-shadow:var(--dash-shadow);padding:20px}.dashboard .card.glow{background:linear-gradient(160deg,rgba(139,124,255,.12),rgba(20,24,31,.95) 48%,rgba(15,18,23,.97));border-color:rgba(139,124,255,.2)}.dashboard .section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:12px}.dashboard .section-title{font-size:15px;font-weight:730;letter-spacing:-.015em}.dashboard .section-label{color:var(--dash-muted);font-size:12px;line-height:1.55;margin-top:4px}.dashboard .metrics{gap:15px}.dashboard .metric-box{min-height:118px;padding:20px;border:1px solid var(--dash-line);border-radius:16px;background:linear-gradient(180deg,rgba(20,24,31,.95),rgba(15,18,23,.96));box-shadow:var(--dash-shadow);position:relative;overflow:hidden}.dashboard .metric-box:after{content:"";position:absolute;width:90px;height:90px;border-radius:50%;right:-36px;top:-38px;background:radial-gradient(circle,rgba(139,124,255,.15),transparent 70%)}.dashboard .metric-label{padding:0;color:var(--dash-muted);font-size:11px;font-weight:700}.dashboard .metric-value{font-size:31px;font-weight:800;letter-spacing:-.045em;margin-top:12px;line-height:1}.dashboard .stack{display:grid;gap:10px}.dashboard .row{min-width:0;padding:14px 16px;border:1px solid var(--dash-line);border-radius:13px;background:linear-gradient(180deg,rgba(20,24,31,.92),rgba(15,18,23,.94));box-shadow:0 10px 30px rgba(0,0,0,.12)}.dashboard .row-title{font-size:13px;font-weight:680;letter-spacing:-.01em}.dashboard .row-meta{color:var(--dash-muted2);font-size:10.5px;line-height:1.5;margin-top:4px}.dashboard .badge{border-color:var(--dash-line);border-radius:999px;padding:5px 8px;font-size:9.5px;font-weight:780}.dashboard .badge.green{color:#75e6aa;background:rgba(80,216,144,.07);border-color:rgba(80,216,144,.18)}.dashboard .badge.blue{color:#a9b8ff;background:rgba(139,124,255,.08);border-color:rgba(139,124,255,.2)}.dashboard .badge.muted{color:var(--dash-muted);background:rgba(146,155,173,.04)}.dashboard .btn{min-height:34px;padding:7px 11px;border-radius:10px;border-color:var(--dash-line);background:linear-gradient(180deg,var(--dash-surface3),var(--dash-surface2));font-size:10.5px}.dashboard .tree{gap:8px}.dashboard .tree-node{padding:11px 13px;border:1px solid var(--dash-line);border-radius:12px;background:rgba(17,20,26,.72)}.dashboard .mono{overflow-wrap:anywhere}.dashboard .empty{padding:34px 16px;text-align:center;color:var(--dash-muted2);font-size:12px}
@media(max-width:1000px){.dash-shell{grid-template-columns:220px minmax(0,1fr)}.dash-main{padding:34px 28px 56px}.dashboard .span3{grid-column:span 6}}@media(max-width:760px){.dash-shell{display:block}.dash-sidebar{position:relative;height:auto;border-right:0;border-bottom:1px solid var(--dash-line-soft);padding:12px}.dash-brand{padding:3px 6px 11px}.dash-nav-label,.dash-status,.dash-foot{display:none}.dash-nav{display:flex;overflow-x:auto;gap:5px}.dash-nav a{white-space:nowrap;flex:0 0 auto;padding:8px 10px}.dash-main{padding:24px 15px 46px}.dash-title{font-size:28px}.dashboard .metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.dashboard .span3,.dashboard .span4,.dashboard .span6,.dashboard .span8,.dashboard .span12{grid-column:1/-1}}@media(max-width:520px){.dashboard .metrics{grid-template-columns:1fr}}
`

func icon(path string) string {
	return `<svg viewBox="0 0 24 24" aria-hidden="true">` + path + `</svg>`
}

func dashboardPage(title, subtitle, body string) string {
	brand := `<div class="dash-brand"><img class="dash-logo" src="/assets/codelocal-icon.png" alt=""><span class="dash-brand-name">CodeLocal</span><span class="dash-brand-tag">CLOUD</span></div>`
	nav := `<div class="dash-nav-label">Control plane</div><nav class="dash-nav" id="dashboard-nav">` +
		`<a href="/dashboard" data-route="/dashboard"><span class="dash-nav-icon">` + icon(`<rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/>`) + `</span>Overview</a>` +
		`<a href="/dashboard/workspaces" data-route="/dashboard/workspaces"><span class="dash-nav-icon">` + icon(`<path d="M3.5 7.5h6l2-2h9v13.5H3.5z"/><path d="M3.5 9.5h17"/>`) + `</span>Workspaces</a>` +
		`<a href="/dashboard/devices" data-route="/dashboard/devices"><span class="dash-nav-icon">` + icon(`<rect x="5" y="3" width="14" height="18" rx="3"/><path d="M9.5 6h5M11 18h2"/>`) + `</span>Devices</a>` +
		`<a href="/dashboard/usage" data-route="/dashboard/usage"><span class="dash-nav-icon">` + icon(`<path d="M4 18V9M10 18V5M16 18v-7M22 18V3"/>`) + `</span>Token usage</a>` +
		`<a href="/dashboard/connect" data-route="/dashboard/connect"><span class="dash-nav-icon">` + icon(`<path d="M8 12h8M13 9l3 3-3 3"/><path d="M5 5.5h6M5 18.5h6"/>`) + `</span>Connect ChatGPT</a>` +
		`<a href="/dashboard/security" data-route="/dashboard/security"><span class="dash-nav-icon">` + icon(`<path d="M12 3l7 3v5c0 4.6-2.8 8.3-7 10-4.2-1.7-7-5.4-7-10V6z"/><path d="M9.5 12l1.7 1.7 3.5-4"/>`) + `</span>Security</a>` +
		`</nav>`
	status := `<div class="dash-spacer"></div><div class="dash-status"><div class="dash-status-title"><span class="dash-status-dot"></span>Cloud connected</div><div class="dash-status-copy">Local source code and secrets stay on your machine.</div></div><div class="dash-foot"><div class="dash-account" id="dashboard-account" hidden><div class="dash-avatar">CL</div><div class="dash-account-copy"><div class="dash-account-email" id="dashboard-email"></div><div class="dash-account-meta">CodeLocal account</div></div></div><div id="dashboard-foot-actions"></div></div>`
	script := `<script>(()=>{const path=location.pathname;const labels={'/dashboard':'Overview','/dashboard/workspaces':'Workspaces','/dashboard/devices':'Devices','/dashboard/usage':'Token usage','/dashboard/connect':'Connect ChatGPT','/dashboard/security':'Security','/dashboard/admin':'Admin'};document.querySelectorAll('[data-route]').forEach(a=>{if(path===a.getAttribute('data-route'))a.classList.add('active')});const heading=document.getElementById('dashboard-title');if(heading&&labels[path])heading.textContent=labels[path];const emailSource=document.querySelector('[data-dashboard-email]');if(emailSource){const email=emailSource.getAttribute('data-dashboard-email')||'';const target=document.getElementById('dashboard-email');if(target)target.textContent=email;const account=document.getElementById('dashboard-account');if(account)account.hidden=!email}const legacy=[...document.querySelectorAll('.page-body > .actions')].find(el=>el.querySelector('form[action="/logout"]'));if(legacy){const admin=legacy.querySelector('a[href="/dashboard/admin"]');if(admin){const copy=admin.cloneNode(true);copy.className='';copy.innerHTML='<span class="dash-nav-icon"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v5c0 4.6-2.8 8.3-7 10-4.2-1.7-7-5.4-7-10V6z"/><path d="M9.5 12l1.7 1.7 3.5-4"/></svg></span>Admin';copy.dataset.route='/dashboard/admin';document.getElementById('dashboard-nav')?.appendChild(copy);if(path==='/dashboard/admin')copy.classList.add('active')}const form=legacy.querySelector('form[action="/logout"]');if(form)document.getElementById('dashboard-foot-actions')?.appendChild(form);legacy.remove()}})();</script>`
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="color-scheme" content="dark"><link rel="icon" href="/favicon.ico"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><title>` + Escape(title) + ` · CodeLocal</title><style>` + baseStyles + dashboardStyles + `</style></head><body class="dashboard"><div class="dash-shell"><aside class="dash-sidebar">` + brand + nav + status + `</aside><main class="dash-main"><header class="dash-top"><div><div class="dash-eyebrow">CodeLocal Cloud</div><h1 class="dash-title" id="dashboard-title">` + Escape(title) + `</h1><div class="dash-sub">` + Escape(subtitle) + `</div></div></header><div class="page-body">` + body + `</div></main></div>` + script + `</body></html>`
}

func Page(title, subtitle, body string) string {
	if strings.Contains(title, "CodeLocal Cloud") {
		return dashboardPage(title, subtitle, body)
	}
	return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>` + Escape(title) + ` · CodeLocal</title><style>` + baseStyles + `</style></head><body><main class="shell"><div class="brand"><span class="dot"></span>CodeLocal</div><section class="card"><h1>` + Escape(title) + `</h1><div class="sub">` + Escape(subtitle) + `</div>` + body + `</section></main></body></html>`
}

func Hidden(fields map[string]string) string {
	var out strings.Builder
	for key, value := range fields {
		out.WriteString(`<input type="hidden" name="` + Escape(key) + `" value="` + Escape(value) + `">`)
	}
	return out.String()
}
