package codequality

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

const qualityFixture = `package sample

// comment-only line
func DispatchOrder(a, b, c int) int {
	x := a + b
	y := x * c
	if y > 0 && a > 0 {
		for i := 0; i < c; i++ {
			y += i
		}
	}
	return y + 1
}
`

func strictGoPolicy() LanguagePolicy {
	return normalizeLanguagePolicy(LanguagePolicy{
		MaxFileLines: 5, MaxFunctionLines: 4, MaxNestingDepth: 1, MaxCyclomaticComplexity: 2, MaxParameters: 2,
		SingleResponsibility: true,
		Severity: map[string]string{
			RuleMaxFileLines:            SeverityBlocking,
			RuleMaxFunctionLines:        SeverityBlocking,
			RuleMaxNestingDepth:         SeverityBlocking,
			RuleMaxCyclomaticComplexity: SeverityBlocking,
			RuleMaxParameters:           SeverityBlocking,
		},
		Orchestrators: OrchestratorPolicy{Enabled: true, NamePatterns: []string{"Dispatch*"}, MaxOwnedStatements: 1, Severity: SeverityBlocking},
	})
}

func TestExecutableLOCExcludesBlankAndCommentOnlyLines(t *testing.T) {
	got := executableLOC([]byte("package p\n\n// comment\nfunc f() {\n\tx := 1 // inline comment\n\t_ = x\n}\n"))
	if got != 5 {
		t.Fatalf("executable LOC=%d want 5 token-bearing lines", got)
	}
}

func TestGoAnalyzerReportsDeterministicStructuralLimits(t *testing.T) {
	metrics, findings := analyzeGoFile("sample.go", []byte(qualityFixture), strictGoPolicy())
	if metrics.ExecutableLOC <= 5 || metrics.Functions != 1 {
		t.Fatalf("unexpected file metrics: %#v", metrics)
	}
	seen := map[string]Finding{}
	for _, finding := range findings {
		seen[finding.Rule] = finding
	}
	for _, rule := range []string{RuleMaxFileLines, RuleMaxFunctionLines, RuleMaxNestingDepth, RuleMaxCyclomaticComplexity, RuleMaxParameters, RuleOrchestratorOwnership} {
		finding, ok := seen[rule]
		if !ok {
			t.Fatalf("missing deterministic quality finding %q: %#v", rule, findings)
		}
		if finding.Severity != SeverityBlocking || finding.Path != "sample.go" {
			t.Fatalf("unexpected %s finding: %#v", rule, finding)
		}
	}
}

func TestSingleResponsibilityIsStructuralProxyAndAdvisoryByDefault(t *testing.T) {
	policy := strictGoPolicy()
	delete(policy.Severity, RuleSingleResponsibility)
	_, findings := analyzeGoFile("sample.go", []byte(qualityFixture), policy)
	for _, finding := range findings {
		if finding.Rule == RuleSingleResponsibility {
			if finding.Severity != SeverityAdvisory || !strings.Contains(strings.ToLower(finding.Message), "structural proxy") {
				t.Fatalf("single-responsibility proxy overclaimed semantics: %#v", finding)
			}
			return
		}
	}
	// The proxy requires multiple structural pressure signals and is allowed to
	// remain silent when a function does not cross that conservative threshold.
}

func TestOrchestratorDetectionSupportsExplicitFunctionsAndPatterns(t *testing.T) {
	policy := strictGoPolicy()
	if !matchesOrchestrator("DispatchOrder", policy.Orchestrators) {
		t.Fatal("configured Dispatch* orchestrator pattern did not match")
	}
	policy.Orchestrators.NamePatterns = nil
	policy.Orchestrators.ExplicitFunctions = []string{"HandleOrder"}
	if !matchesOrchestrator("HandleOrder", policy.Orchestrators) || matchesOrchestrator("DispatchOrder", policy.Orchestrators) {
		t.Fatal("explicit orchestrator roles were not authoritative")
	}
}

func TestAnalyzeExemptsTestsGeneratedMigrationsAndConfiguredPaths(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		"regular.go":             qualityFixture,
		"regular_test.go":        qualityFixture,
		"generated.go":           "// Code generated by x. DO NOT EDIT.\npackage sample\nfunc Huge(){}\n",
		"migrations/001_init.go": qualityFixture,
		"framework/handler.go":   qualityFixture,
	}
	for relative, content := range files {
		path := filepath.Join(root, filepath.FromSlash(relative))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.MkdirAll(filepath.Join(root, ".codelocal"), 0o755); err != nil {
		t.Fatal(err)
	}
	config := `{"schemaVersion":1,"languages":{"go":{"maxFileLines":2}},"exemptions":{"generated":true,"tests":true,"migrations":true,"paths":["framework/**"]}}`
	if err := os.WriteFile(filepath.Join(root, ".codelocal", "quality.json"), []byte(config), 0o644); err != nil {
		t.Fatal(err)
	}
	report := Analyze(root, []string{"regular.go", "regular_test.go", "generated.go", "migrations/001_init.go", "framework/handler.go"})
	if report.ConfigSource != "project" || report.FilesAnalyzed != 1 || report.FilesExempt != 4 {
		t.Fatalf("quality exemptions were not applied: %#v", report)
	}
	if len(report.Findings) == 0 || report.Findings[0].Path != "regular.go" {
		t.Fatalf("unexpected quality findings after exemptions: %#v", report.Findings)
	}
}

func TestAnalyzeDefaultsNeverCreateBlockingFindings(t *testing.T) {
	root := t.TempDir()
	if err := os.WriteFile(filepath.Join(root, "sample.go"), []byte(qualityFixture), 0o644); err != nil {
		t.Fatal(err)
	}
	report := Analyze(root, []string{"sample.go"})
	if report.ConfigSource != "defaults" || report.BlockingCount != 0 {
		t.Fatalf("safe default quality policy unexpectedly blocks repository: %#v", report)
	}
}
