export function escapeHtml(value: unknown) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function formatTime(value?: number) {
  if (!value) return "—";
  return new Intl.DateTimeFormat("en", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
}

const styles = `
:root{
  color-scheme:dark;
  --bg:#090a0d;--bg2:#0d0f13;--surface:#11141a;--surface2:#161a21;--surface3:#1b2029;
  --line:#242a35;--line-soft:#1c212a;--text:#f7f8fb;--muted:#929bad;--muted2:#6f7889;
  --accent:#8b7cff;--accent2:#5ca9ff;--green:#50d890;--red:#ff6978;--yellow:#f2bd57;--cyan:#62d8f4;
  --shadow:0 24px 70px rgba(0,0,0,.32);--radius:16px;--radius-sm:11px
}
*{box-sizing:border-box}html,body{max-width:100%;overflow-x:hidden}html{background:var(--bg)}
body{margin:0;color:var(--text);font-family:Inter,ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;line-height:1.45;background:
 radial-gradient(900px 520px at 8% -14%,rgba(139,124,255,.16),transparent 60%),
 radial-gradient(760px 500px at 100% 8%,rgba(92,169,255,.08),transparent 62%),var(--bg)}
button,input,select,textarea{font:inherit}a{color:inherit;text-decoration:none}code,.mono{font-family:"SFMono-Regular",Consolas,"Liberation Mono",monospace}
.shell{min-height:100vh;width:100%;display:grid;grid-template-columns:248px minmax(0,1fr)}
.sidebar{position:sticky;top:0;height:100vh;min-width:0;padding:20px 14px;border-right:1px solid var(--line-soft);background:rgba(9,10,13,.84);backdrop-filter:blur(24px);display:flex;flex-direction:column}
.brand{display:flex;align-items:center;gap:11px;padding:5px 8px 21px}.logo{width:31px;height:31px;flex:0 0 31px;display:grid;place-items:center;border-radius:10px;background:linear-gradient(145deg,var(--accent),var(--accent2));box-shadow:0 10px 28px rgba(112,126,255,.25);font-weight:900;font-size:14px}.brand-name{font-size:15px;font-weight:780;letter-spacing:-.025em}.brand-tag{margin-left:auto;border:1px solid var(--line);background:var(--surface);color:var(--muted);font-size:9px;font-weight:800;letter-spacing:.08em;padding:4px 6px;border-radius:999px}
.nav-label{padding:10px 10px 6px;color:var(--muted2);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.12em}.nav{display:grid;gap:3px}.nav a{display:flex;align-items:center;gap:10px;padding:9px 10px;border-radius:10px;color:var(--muted);font-size:13px;font-weight:600;transition:.15s ease}.nav a:hover{background:rgba(255,255,255,.035);color:var(--text)}.nav a.active{background:linear-gradient(90deg,rgba(139,124,255,.13),rgba(92,169,255,.06));box-shadow:inset 0 0 0 1px rgba(139,124,255,.13);color:#fff}.nav-icon{width:19px;height:19px;display:grid;place-items:center;color:inherit;font-size:13px}.nav a.active .nav-icon{color:#b8afff}
.sidebar-spacer{flex:1}.sidebar-status{margin:14px 7px;padding:12px;border:1px solid var(--line-soft);border-radius:12px;background:rgba(17,20,26,.72)}.sidebar-status-title{display:flex;align-items:center;gap:8px;font-size:11px;font-weight:700}.status-dot{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--muted2);box-shadow:0 0 0 3px rgba(146,155,173,.06)}.status-dot.green{background:var(--green);box-shadow:0 0 0 3px rgba(80,216,144,.09),0 0 14px rgba(80,216,144,.2)}.sidebar-status-copy{color:var(--muted2);font-size:10px;margin-top:5px;line-height:1.45}.sidebar-foot{padding:12px 8px 2px;border-top:1px solid var(--line-soft);display:flex;align-items:center;gap:9px}.avatar{width:28px;height:28px;border-radius:9px;display:grid;place-items:center;background:var(--surface3);border:1px solid var(--line);font-size:11px;font-weight:800}.account{min-width:0;flex:1}.account-email{white-space:nowrap;overflow:hidden;text-overflow:ellipsis;font-size:11px;font-weight:650}.account-meta{font-size:10px;color:var(--muted2)}
.main{min-width:0;width:100%;max-width:1320px;margin:0 auto;padding:38px 44px 64px}.top{display:flex;justify-content:space-between;align-items:flex-start;gap:22px;margin-bottom:28px}.top-copy{min-width:0}.eyebrow{display:flex;align-items:center;gap:7px;color:var(--muted2);font-size:10px;font-weight:800;text-transform:uppercase;letter-spacing:.13em}.h1{font-size:31px;font-weight:790;letter-spacing:-.04em;margin:7px 0 4px}.sub{max-width:760px;color:var(--muted);font-size:13px;line-height:1.6}.top-actions{display:flex;align-items:center;gap:9px;flex-wrap:wrap}
.grid{min-width:0;display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:15px}.span3{grid-column:span 3}.span4{grid-column:span 4}.span5{grid-column:span 5}.span6{grid-column:span 6}.span7{grid-column:span 7}.span8{grid-column:span 8}.span12{grid-column:span 12}
.card{min-width:0;border:1px solid var(--line);border-radius:var(--radius);background:linear-gradient(180deg,rgba(20,24,31,.95),rgba(15,18,23,.96));box-shadow:var(--shadow);padding:20px}.card.flat{box-shadow:none}.card.glow{background:linear-gradient(160deg,rgba(139,124,255,.12),rgba(20,24,31,.95) 48%,rgba(15,18,23,.97));border-color:rgba(139,124,255,.2)}
.metric-card{position:relative;overflow:hidden;min-height:118px}.metric-card:after{content:"";position:absolute;width:90px;height:90px;border-radius:50%;right:-36px;top:-38px;background:radial-gradient(circle,rgba(139,124,255,.15),transparent 70%)}.metric-label{color:var(--muted);font-size:11px;font-weight:700}.metric{font-size:31px;font-weight:800;letter-spacing:-.045em;margin-top:12px}.metric-sub{margin-top:3px;color:var(--muted2);font-size:10px}.metric-state{font-size:18px;letter-spacing:-.02em;margin-top:15px}
.title{font-size:15px;font-weight:730;letter-spacing:-.015em}.label{color:var(--muted);font-size:12px;line-height:1.55}.section-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px;margin-bottom:12px}.section-head .label{margin-top:4px}.divider{height:1px;background:var(--line-soft);margin:16px 0}
.list{display:grid}.row{min-width:0;display:flex;align-items:center;justify-content:space-between;gap:14px;padding:14px 0;border-bottom:1px solid var(--line-soft)}.row:first-child{padding-top:4px}.row:last-child{border-bottom:0;padding-bottom:4px}.row-main{min-width:0;flex:1}.row-title{display:flex;align-items:center;gap:8px;min-width:0;font-size:13px;font-weight:680}.row-title-text{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.row-meta{color:var(--muted2);font-size:10.5px;margin-top:4px;overflow-wrap:anywhere;word-break:break-word;line-height:1.5}.entity{display:flex;align-items:center;gap:11px;min-width:0}.entity-icon{width:34px;height:34px;flex:0 0 34px;border-radius:10px;display:grid;place-items:center;background:var(--surface3);border:1px solid var(--line);font-size:13px;color:#c6cdfd}.entity-icon svg{width:18px;height:18px;display:block;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}.entity-copy{min-width:0}
.badge{display:inline-flex;align-items:center;gap:6px;flex:0 0 auto;max-width:100%;border:1px solid var(--line);border-radius:999px;padding:5px 8px;color:var(--muted);font-size:9.5px;font-weight:780;white-space:nowrap}.badge:before{content:"";width:5px;height:5px;border-radius:50%;background:currentColor;opacity:.72}.badge.green{color:#75e6aa;background:rgba(80,216,144,.07);border-color:rgba(80,216,144,.18)}.badge.red{color:#ff929c;background:rgba(255,105,120,.07);border-color:rgba(255,105,120,.18)}.badge.blue{color:#a9b8ff;background:rgba(139,124,255,.08);border-color:rgba(139,124,255,.2)}.badge.yellow{color:#ffd37e;background:rgba(242,189,87,.07);border-color:rgba(242,189,87,.18)}.badge.muted{color:var(--muted);background:rgba(146,155,173,.04)}
.actions{display:flex;align-items:center;gap:7px;flex-wrap:wrap;flex:0 0 auto}.btn{appearance:none;border:1px solid var(--line);background:linear-gradient(180deg,var(--surface3),var(--surface2));color:var(--text);min-height:36px;padding:8px 12px;border-radius:10px;font-size:11px;font-weight:700;cursor:pointer;display:inline-flex;align-items:center;justify-content:center;gap:7px;transition:.15s ease}.btn:hover{transform:translateY(-1px);border-color:#343b48;filter:brightness(1.06)}.btn:active{transform:translateY(0)}.btn[disabled]{opacity:.38;cursor:not-allowed;transform:none;filter:none}.btn.primary{border-color:transparent;background:linear-gradient(135deg,#8879ff,#5b9fff);box-shadow:0 8px 24px rgba(105,117,255,.2)}.btn.danger{color:#ff9aa4;border-color:rgba(255,105,120,.2);background:rgba(255,105,120,.055)}.btn.ghost{background:transparent}.btn.small{min-height:31px;padding:6px 9px;font-size:10px}.btn-icon{font-size:12px;opacity:.9}
form{min-width:0;margin:0}.form{display:grid;gap:13px}.field{display:grid;gap:6px}.field label{color:var(--muted);font-size:10.5px;font-weight:700}.input,.select,.textarea{width:100%;min-width:0;max-width:100%;border:1px solid var(--line);background:#0c0f14;color:var(--text);border-radius:10px;padding:10px 11px;outline:none;font-size:12px}.input:focus,.select:focus,.textarea:focus{border-color:rgba(139,124,255,.72);box-shadow:0 0 0 3px rgba(139,124,255,.08)}.textarea{min-height:88px;resize:vertical}.hint{color:var(--muted2);font-size:10px;line-height:1.5}
.alert{border:1px solid rgba(255,105,120,.2);background:rgba(255,105,120,.06);color:#ffb1b9;border-radius:11px;padding:10px 12px;font-size:11px;margin-bottom:14px}.alert.success{border-color:rgba(80,216,144,.2);background:rgba(80,216,144,.06);color:#95ebbd}.empty{padding:38px 16px;text-align:center;color:var(--muted2);font-size:12px}.empty-icon{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;margin:0 auto 11px;background:var(--surface3);border:1px solid var(--line);color:var(--muted)}.empty-icon svg{width:20px;height:20px;display:block;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}
code,.code{background:#0b0d11;border:1px solid var(--line-soft);border-radius:7px;padding:2px 5px;font-size:10.5px;overflow-wrap:anywhere}.code-block{position:relative;max-width:100%;background:#0b0e13;border:1px solid var(--line);border-radius:12px;padding:14px;color:#dce3f6;font-size:11px;white-space:pre-wrap;overflow:auto;overflow-wrap:anywhere;word-break:break-word}.copy-row{display:flex;align-items:center;gap:9px}.copy-row .code-block{flex:1}.kv{display:grid;grid-template-columns:140px minmax(0,1fr);gap:10px;padding:10px 0;border-bottom:1px solid var(--line-soft);font-size:11px}.kv:last-child{border-bottom:0}.kv-key{color:var(--muted2)}.kv-value{min-width:0;overflow-wrap:anywhere}
.activity{display:flex;gap:11px;padding:11px 0;border-bottom:1px solid var(--line-soft)}.activity:last-child{border-bottom:0}.activity-icon{width:27px;height:27px;flex:0 0 27px;border:1px solid var(--line);background:var(--surface3);border-radius:9px;display:grid;place-items:center;color:#aeb7ca;font-size:10px}.activity-title{font-size:11px;font-weight:660}.activity-meta{font-size:9.5px;color:var(--muted2);margin-top:3px}
.auth-wrap{min-height:100vh;display:grid;place-items:center;padding:24px}.auth{width:min(430px,100%)}.auth .brand{justify-content:center;padding-bottom:18px}.auth .brand-tag{display:none}.auth .card{padding:27px}.auth h1{font-size:25px;letter-spacing:-.035em;margin:0 0 6px}.auth p{color:var(--muted);font-size:12px;margin:0 0 22px;line-height:1.6}.auth-switch{text-align:center;color:var(--muted);font-size:11px;margin-top:16px}.auth-switch a{color:#b4adff}.muted{color:var(--muted)}
dialog{width:min(440px,calc(100vw - 30px));padding:0;border:1px solid var(--line);border-radius:16px;background:#11151b;color:var(--text);box-shadow:0 32px 100px rgba(0,0,0,.55)}dialog::backdrop{background:rgba(3,5,8,.72);backdrop-filter:blur(5px)}.modal{padding:22px}.modal-icon{width:38px;height:38px;display:grid;place-items:center;border-radius:11px;background:rgba(255,105,120,.08);border:1px solid rgba(255,105,120,.18);color:#ff8e99;margin-bottom:14px}.modal-title{font-size:17px;font-weight:760;letter-spacing:-.02em}.modal-copy{color:var(--muted);font-size:11.5px;line-height:1.65;margin-top:7px}.modal-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:19px}
@media(max-width:980px){.shell{grid-template-columns:218px minmax(0,1fr)}.main{padding:32px 28px 56px}.span3{grid-column:span 6}.span4,.span5,.span6,.span7,.span8{grid-column:span 12}}
@media(max-width:760px){.shell{display:block}.sidebar{position:relative;height:auto;border-right:0;border-bottom:1px solid var(--line-soft);padding:12px}.brand{padding:3px 6px 11px}.nav-label,.sidebar-status,.sidebar-foot{display:none}.nav{display:flex;overflow-x:auto;gap:5px}.nav a{white-space:nowrap;flex:0 0 auto;padding:8px 10px}.main{padding:24px 15px 46px}.top{flex-direction:column;margin-bottom:20px}.top-actions{width:100%}.h1{font-size:27px}.span3,.span4,.span5,.span6,.span7,.span8{grid-column:span 12}.row{align-items:flex-start;flex-wrap:wrap}.actions{width:100%;justify-content:flex-start}.section-head{flex-direction:column}.copy-row{align-items:stretch;flex-direction:column}.kv{grid-template-columns:1fr;gap:3px}.auth-wrap{padding:14px}.auth .card{padding:22px 17px}}
`;

const premiumStyles = `
:root{
  color-scheme:light dark;
  --bg:#f5f5f7;--bg2:#ececf1;--surface:rgba(255,255,255,.78);--surface2:rgba(255,255,255,.62);--surface3:rgba(246,246,249,.88);
  --line:rgba(29,29,31,.1);--line-soft:rgba(29,29,31,.065);--text:#1d1d1f;--muted:#6e6e73;--muted2:#8e8e93;
  --accent:#0071e3;--accent2:#6e5cff;--green:#24a148;--red:#d70015;--yellow:#b86400;--cyan:#0a84ff;
  --shadow:0 20px 60px rgba(15,23,42,.08),0 2px 10px rgba(15,23,42,.045);--radius:22px;--radius-sm:14px;
  --sidebar:rgba(248,248,250,.72);--button:#fff;--field:rgba(255,255,255,.82);--code:#f1f1f5;--focus:rgba(0,113,227,.15)
}
@media(prefers-color-scheme:dark){:root{
  --bg:#090a0d;--bg2:#111319;--surface:rgba(24,26,32,.76);--surface2:rgba(27,29,36,.62);--surface3:rgba(34,37,45,.8);
  --line:rgba(255,255,255,.11);--line-soft:rgba(255,255,255,.065);--text:#f5f5f7;--muted:#a1a1a6;--muted2:#77777d;
  --accent:#2997ff;--accent2:#8e7dff;--green:#4ad969;--red:#ff453a;--yellow:#ffd60a;--cyan:#64d2ff;
  --shadow:0 28px 80px rgba(0,0,0,.3),0 2px 12px rgba(0,0,0,.22);--sidebar:rgba(13,14,18,.73);--button:rgba(46,48,57,.9);--field:rgba(17,19,24,.82);--code:#12141a;--focus:rgba(41,151,255,.18)
}}
html{background:var(--bg);scroll-behavior:smooth}
body{position:relative;min-height:100vh;color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","SF Pro Text","Helvetica Neue",Arial,sans-serif;line-height:1.45;background:
  radial-gradient(900px 560px at 78% -15%,rgba(0,113,227,.14),transparent 62%),
  radial-gradient(720px 520px at 28% 110%,rgba(110,92,255,.1),transparent 66%),var(--bg)}
body:before{content:"";position:fixed;inset:0;pointer-events:none;z-index:-1;background:linear-gradient(115deg,rgba(255,255,255,.22),transparent 32%,transparent 72%,rgba(255,255,255,.08));opacity:.65}
button,input,select,textarea{font-family:-apple-system,BlinkMacSystemFont,"SF Pro Text","Helvetica Neue",Arial,sans-serif}
.shell{grid-template-columns:264px minmax(0,1fr)}
.sidebar{padding:20px 16px 16px;border-right:1px solid var(--line-soft);background:var(--sidebar);backdrop-filter:saturate(180%) blur(32px);-webkit-backdrop-filter:saturate(180%) blur(32px)}
.brand{gap:12px;padding:3px 8px 24px}.logo{width:38px;height:38px;flex:0 0 38px;display:block;object-fit:cover;border-radius:12px;background:#0b1020;box-shadow:0 10px 28px rgba(30,64,175,.18),inset 0 0 0 .5px rgba(255,255,255,.32)}
.brand-name{font-size:16px;font-weight:700;letter-spacing:-.025em}.brand-tag{border:0;background:rgba(0,113,227,.09);color:var(--accent);font-size:9px;font-weight:750;letter-spacing:.11em;padding:5px 8px}
.nav-label{padding:9px 12px 8px;color:var(--muted2);font-size:10px;font-weight:650;letter-spacing:.1em}
.nav{gap:5px}.nav a{position:relative;gap:11px;min-height:42px;padding:10px 12px;border-radius:13px;color:var(--muted);font-size:13px;font-weight:560;transition:background .2s ease,color .2s ease,transform .2s ease}
.nav a:hover{background:rgba(127,127,127,.08);color:var(--text);transform:translateX(1px)}.nav a.active{background:rgba(0,113,227,.1);box-shadow:inset 0 0 0 .5px rgba(0,113,227,.14);color:var(--accent)}
.nav-icon{width:20px;height:20px;font-size:0}.nav-icon svg{width:19px;height:19px;display:block;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}.nav a.active .nav-icon{color:var(--accent)}
.sidebar-status{margin:16px 6px;padding:14px;border:1px solid var(--line-soft);border-radius:17px;background:var(--surface2);box-shadow:inset 0 1px 0 rgba(255,255,255,.28)}
.sidebar-status-title{font-size:11px;font-weight:650}.sidebar-status-copy{font-size:10.5px;line-height:1.55;margin-top:6px}.status-dot{width:7px;height:7px}.status-dot.green{box-shadow:0 0 0 4px rgba(36,161,72,.1),0 0 16px rgba(36,161,72,.25)}
.sidebar-foot{padding:14px 6px 1px;gap:10px}.avatar{width:32px;height:32px;border:0;border-radius:50%;background:linear-gradient(145deg,rgba(0,113,227,.15),rgba(110,92,255,.13));color:var(--accent);font-size:12px}.account-email{font-size:11.5px;font-weight:590}.account-meta{font-size:9.5px}
.main{min-width:0;width:100%;max-width:1380px;margin:0 auto;padding:50px 52px 76px}
.top{align-items:center;gap:28px;margin-bottom:32px}.eyebrow{color:var(--muted2);font-size:10px;font-weight:680;letter-spacing:.11em}.h1{font-size:38px;font-weight:700;letter-spacing:-.045em;line-height:1.08;margin:9px 0 7px}.sub{max-width:760px;color:var(--muted);font-size:14px;line-height:1.58;letter-spacing:-.006em}
.grid{gap:18px}.card{min-width:0;border:1px solid var(--line);border-radius:var(--radius);background:var(--surface);backdrop-filter:saturate(155%) blur(24px);-webkit-backdrop-filter:saturate(155%) blur(24px);box-shadow:var(--shadow);padding:24px;transition:transform .22s ease,box-shadow .22s ease,border-color .22s ease}
.card:hover{border-color:rgba(127,127,127,.18);box-shadow:0 24px 72px rgba(15,23,42,.105),0 2px 12px rgba(15,23,42,.05)}
.card.glow{background:linear-gradient(145deg,rgba(0,113,227,.105),var(--surface) 48%,rgba(110,92,255,.055));border-color:rgba(0,113,227,.16)}
.metric-card{min-height:144px;padding:22px 24px}.metric-card:before{content:"";position:absolute;left:24px;top:20px;width:30px;height:4px;border-radius:999px;background:linear-gradient(90deg,var(--accent),var(--accent2));box-shadow:0 4px 16px rgba(0,113,227,.22)}.metric-card:after{width:150px;height:150px;right:-68px;top:-78px;background:radial-gradient(circle,rgba(0,113,227,.12),transparent 67%)}
.metric-label{padding-top:15px;color:var(--muted);font-size:11px;font-weight:620}.metric{font-size:38px;font-weight:690;letter-spacing:-.05em;margin-top:11px;line-height:1}.metric-sub{margin-top:8px;color:var(--muted2);font-size:10.5px}
.title{font-size:17px;font-weight:650;letter-spacing:-.023em}.label{font-size:12px;line-height:1.6}.section-head{gap:20px;margin-bottom:14px}.divider{background:var(--line-soft);margin:18px 0}
.row{gap:16px;padding:15px 0;transition:background .18s ease}.row-title{font-size:13px;font-weight:620}.row-meta{font-size:10.5px;line-height:1.55}.entity{gap:13px}.entity-icon{width:38px;height:38px;flex:0 0 38px;border:0;border-radius:12px;background:linear-gradient(145deg,rgba(0,113,227,.11),rgba(110,92,255,.08));color:var(--accent);font-size:14px;box-shadow:inset 0 0 0 .5px rgba(0,113,227,.12)}
.badge{border-color:transparent;border-radius:999px;padding:6px 10px;font-size:9.5px;font-weight:650;letter-spacing:.01em}.badge.green{color:var(--green);background:rgba(36,161,72,.1);border-color:transparent}.badge.red{color:var(--red);background:rgba(215,0,21,.09);border-color:transparent}.badge.blue{color:var(--accent);background:rgba(0,113,227,.1);border-color:transparent}.badge.yellow{color:var(--yellow);background:rgba(184,100,0,.1);border-color:transparent}.badge.muted{background:rgba(127,127,127,.09)}
.btn{border:1px solid var(--line);background:var(--button);color:var(--text);min-height:40px;padding:9px 15px;border-radius:12px;font-size:11.5px;font-weight:620;box-shadow:0 1px 2px rgba(0,0,0,.035);transition:transform .18s ease,box-shadow .18s ease,background .18s ease,border-color .18s ease}
.btn:hover{transform:translateY(-1px);border-color:rgba(127,127,127,.2);filter:none;box-shadow:0 6px 18px rgba(15,23,42,.09)}.btn:active{transform:scale(.98)}.btn.primary{border-color:transparent;background:linear-gradient(145deg,#1687ed,#0066cc);color:#fff;box-shadow:0 8px 22px rgba(0,102,204,.22),inset 0 1px 0 rgba(255,255,255,.18)}.btn.primary:hover{box-shadow:0 11px 28px rgba(0,102,204,.28)}.btn.danger{color:var(--red);border-color:rgba(215,0,21,.12);background:rgba(215,0,21,.055)}.btn.ghost{background:transparent;box-shadow:none}.btn.small{min-height:33px;padding:7px 10px;font-size:10px}
.input,.select,.textarea{border:1px solid var(--line);background:var(--field);color:var(--text);border-radius:13px;padding:11px 12px;font-size:12px;box-shadow:inset 0 1px 1px rgba(0,0,0,.025)}.input:focus,.select:focus,.textarea:focus{border-color:var(--accent);box-shadow:0 0 0 4px var(--focus)}
.alert{border:0;background:rgba(215,0,21,.075);color:var(--red);border-radius:14px;padding:12px 14px;font-size:11px}.alert.success{border:0;background:rgba(36,161,72,.09);color:var(--green)}
.empty{padding:46px 16px;font-size:12px}.empty-icon{width:46px;height:46px;border:0;border-radius:15px;background:rgba(127,127,127,.08);color:var(--muted)}
code,.code{background:var(--code);border:1px solid var(--line-soft);border-radius:8px;padding:2px 6px}.code-block{background:var(--code);border:1px solid var(--line);border-radius:16px;padding:16px;color:var(--text);font-size:11px;line-height:1.65;box-shadow:inset 0 1px 1px rgba(0,0,0,.025)}
.activity{gap:12px;padding:13px 0}.activity-icon{width:30px;height:30px;flex:0 0 30px;border:0;background:rgba(0,113,227,.09);border-radius:50%;color:var(--accent)}.activity-title{font-size:11.5px;font-weight:600}.activity-meta{font-size:10px;margin-top:4px}
.auth-wrap{padding:28px;background:radial-gradient(680px 420px at 50% 0,rgba(0,113,227,.15),transparent 70%)}.auth{width:min(460px,100%)}.auth .brand{padding-bottom:24px}.auth .logo{width:48px;height:48px;flex-basis:48px;border-radius:15px}.auth .brand-name{font-size:18px}.auth .card{padding:34px}.auth h1{font-size:29px;font-weight:690;line-height:1.16}.auth p{font-size:13px;line-height:1.65;margin-bottom:24px}.auth-switch{font-size:11.5px}.auth-switch a{color:var(--accent)}
dialog{border:1px solid var(--line);border-radius:22px;background:var(--surface);backdrop-filter:blur(28px);-webkit-backdrop-filter:blur(28px);box-shadow:0 36px 120px rgba(0,0,0,.3)}dialog::backdrop{background:rgba(10,12,18,.46);backdrop-filter:blur(10px)}.modal{padding:26px}.modal-icon{border:0;border-radius:13px;background:rgba(215,0,21,.09);color:var(--red)}.modal-title{font-size:19px;font-weight:670}.modal-copy{font-size:12px;line-height:1.65}.modal-actions{margin-top:22px}
@media(max-width:980px){.shell{grid-template-columns:230px minmax(0,1fr)}.main{padding:38px 30px 60px}.h1{font-size:34px}.span3{grid-column:span 6}.span4,.span5,.span6,.span7,.span8{grid-column:span 12}}
@media(max-width:760px){.shell{display:block}.sidebar{position:sticky;z-index:10;top:0;height:auto;border-right:0;border-bottom:1px solid var(--line-soft);padding:11px 12px}.brand{padding:2px 6px 10px}.logo{width:34px;height:34px;flex-basis:34px;border-radius:11px}.nav-label,.sidebar-status,.sidebar-foot,.brand-tag{display:none}.nav{display:flex;overflow-x:auto;gap:6px;padding-bottom:1px}.nav a{white-space:nowrap;flex:0 0 auto;min-height:38px;padding:8px 11px}.nav-icon{width:18px;height:18px}.main{padding:28px 16px 48px}.top{align-items:flex-start;flex-direction:column;margin-bottom:24px}.top-actions{width:100%}.h1{font-size:31px}.sub{font-size:13px}.grid{gap:14px}.card{padding:20px;border-radius:19px}.metric-card{min-height:126px}.span3,.span4,.span5,.span6,.span7,.span8{grid-column:span 12}.row{align-items:flex-start;flex-wrap:wrap}.actions{width:100%;justify-content:flex-start}.section-head{flex-direction:column}.copy-row{align-items:stretch;flex-direction:column}.kv{grid-template-columns:1fr;gap:3px}.auth-wrap{padding:16px}.auth .card{padding:26px 20px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
`;

const landingStyles = `
.landing{min-height:100vh}.landing-nav{position:sticky;top:0;z-index:20;border-bottom:1px solid var(--line-soft);background:rgba(245,245,247,.76);backdrop-filter:saturate(180%) blur(28px);-webkit-backdrop-filter:saturate(180%) blur(28px)}
@media(prefers-color-scheme:dark){.landing-nav{background:rgba(9,10,13,.76)}}
.landing-nav-inner{width:min(1180px,calc(100% - 40px));min-height:70px;margin:0 auto;display:flex;align-items:center;justify-content:space-between;gap:24px}.landing-brand{display:flex;align-items:center;gap:11px;font-size:16px;font-weight:700;letter-spacing:-.025em}.landing-logo{width:38px;height:38px;border-radius:12px;box-shadow:0 10px 28px rgba(30,64,175,.18)}.landing-links{display:flex;align-items:center;gap:10px}
.landing-main{width:min(1180px,calc(100% - 40px));margin:0 auto}.landing-hero{display:grid;grid-template-columns:minmax(0,1.15fr) minmax(360px,.85fr);align-items:center;gap:72px;padding:100px 0 92px}.landing-kicker{display:inline-flex;align-items:center;gap:9px;color:var(--accent);font-size:12px;font-weight:670}.landing-hero h1{max-width:760px;margin:17px 0 22px;font-size:clamp(48px,7vw,82px);font-weight:710;line-height:.98;letter-spacing:-.062em}.landing-hero-copy{max-width:680px;color:var(--muted);font-size:18px;line-height:1.65;letter-spacing:-.015em}.landing-actions{display:flex;align-items:center;gap:11px;flex-wrap:wrap;margin-top:32px}.landing-actions .btn{min-height:48px;padding:12px 20px;border-radius:14px;font-size:13px}.privacy-note{display:flex;align-items:center;gap:9px;margin-top:23px;color:var(--muted2);font-size:11px}.privacy-note svg{width:17px;height:17px;stroke:var(--green);fill:none;stroke-width:1.8}
.connection-preview{position:relative;min-width:0;padding:28px;border:1px solid var(--line);border-radius:30px;background:var(--surface);box-shadow:0 34px 100px rgba(15,23,42,.14);backdrop-filter:blur(28px)}.preview-head{display:flex;align-items:center;gap:15px}.preview-icon{width:64px;height:64px;border-radius:19px;box-shadow:0 16px 36px rgba(30,64,175,.2)}.preview-title{font-size:20px;font-weight:680}.preview-sub{color:var(--muted);font-size:12px;margin-top:3px}.preview-field{margin-top:20px}.preview-label{color:var(--muted2);font-size:10px;font-weight:650;text-transform:uppercase;letter-spacing:.08em}.preview-value{margin-top:7px;padding:13px 14px;border:1px solid var(--line);border-radius:13px;background:var(--code);font:11.5px/1.5 "SFMono-Regular",Consolas,monospace;overflow-wrap:anywhere}.preview-row{display:flex;justify-content:space-between;align-items:center;gap:18px;margin-top:15px;padding-top:15px;border-top:1px solid var(--line-soft);font-size:12px}.preview-row span:first-child{color:var(--muted)}
.how-section{padding:22px 0 92px}.how-shell{margin-top:34px;padding:30px;border:1px solid var(--line);border-radius:28px;background:linear-gradient(145deg,rgba(0,113,227,.07),var(--surface) 45%,rgba(110,92,255,.055));box-shadow:var(--shadow)}.how-flow{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr) auto minmax(0,1fr) auto minmax(0,1fr) auto minmax(0,1fr);gap:10px;align-items:center}.how-node{min-width:0;padding:16px 12px;border:1px solid var(--line);border-radius:16px;background:var(--surface2);text-align:center;font-size:12px;font-weight:650}.how-arrow{text-align:center;color:var(--accent);font-size:18px;font-weight:700}.how-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-top:20px}.how-card{padding:19px;border:1px solid var(--line-soft);border-radius:18px;background:rgba(127,127,127,.045)}.how-card-title{font-size:14px;font-weight:660}.how-card-copy{margin-top:6px;color:var(--muted);font-size:11.5px;line-height:1.65}.usage-strip{display:flex;align-items:flex-start;gap:12px;margin-top:18px;padding:15px 17px;border-radius:16px;background:rgba(36,161,72,.075);color:var(--muted);font-size:11.5px;line-height:1.6}.usage-strip strong{color:var(--text)}.usage-badge{flex:0 0 auto;padding:5px 8px;border-radius:999px;background:rgba(36,161,72,.12);color:var(--green);font-size:9.5px;font-weight:700;text-transform:uppercase;letter-spacing:.07em}
.setup-section{padding:86px 0}.section-kicker{color:var(--accent);font-size:11px;font-weight:700;text-transform:uppercase;letter-spacing:.11em}.section-title{max-width:780px;margin:10px 0 12px;font-size:clamp(35px,5vw,56px);font-weight:700;line-height:1.06;letter-spacing:-.05em}.section-copy{max-width:720px;color:var(--muted);font-size:15px;line-height:1.65}.setup-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(320px,400px);align-items:start;gap:24px;margin-top:44px}.setup-list{display:grid;gap:16px}.setup-step{display:grid;grid-template-columns:48px minmax(0,1fr);gap:18px;padding:26px;border:1px solid var(--line);border-radius:23px;background:var(--surface);box-shadow:var(--shadow)}.step-number{width:48px;height:48px;display:grid;place-items:center;border-radius:15px;background:rgba(0,113,227,.1);color:var(--accent);font-size:16px;font-weight:720}.step-title{font-size:20px;font-weight:670;letter-spacing:-.025em}.step-summary{margin-top:5px;color:var(--muted);font-size:12.5px;line-height:1.6}.step-details{margin:17px 0 0;padding-left:20px;color:var(--muted);font-size:12px;line-height:1.7}.step-details li+li{margin-top:7px}.step-details strong{color:var(--text);font-weight:620}.step-code{margin-top:15px}.step-note{margin-top:14px;padding:12px 14px;border-radius:13px;background:rgba(0,113,227,.07);color:var(--muted);font-size:11.5px;line-height:1.6}.step-note strong{color:var(--accent)}
.plugin-panel{position:sticky;top:94px;padding:24px;border:1px solid var(--line);border-radius:23px;background:var(--surface);box-shadow:var(--shadow)}.plugin-panel-head{display:flex;align-items:center;gap:14px}.plugin-panel-icon{width:58px;height:58px;border-radius:17px}.plugin-panel-title{font-size:18px;font-weight:670}.plugin-panel-sub{color:var(--muted);font-size:11px;margin-top:3px}.plugin-specs{display:grid;margin-top:20px;border-top:1px solid var(--line-soft)}.plugin-spec{display:grid;grid-template-columns:92px minmax(0,1fr);gap:12px;padding:13px 0;border-bottom:1px solid var(--line-soft);font-size:11.5px}.plugin-spec-key{color:var(--muted2)}.plugin-spec-value{min-width:0;font-weight:590;overflow-wrap:anywhere}.plugin-panel .btn{width:100%;margin-top:12px}.size-ok{display:flex;align-items:center;gap:7px;margin-top:11px;color:var(--green);font-size:10.5px}.size-ok:before{content:"✓";width:18px;height:18px;display:grid;place-items:center;border-radius:50%;background:rgba(36,161,72,.11);font-size:10px;font-weight:800}
.security-section{padding:30px 0 96px}.security-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;margin-top:32px}.security-card{padding:24px;border:1px solid var(--line);border-radius:22px;background:var(--surface)}.security-icon{width:40px;height:40px;display:grid;place-items:center;border-radius:13px;background:rgba(0,113,227,.09);color:var(--accent);font-size:18px}.security-icon svg{width:21px;height:21px;display:block;stroke:currentColor;stroke-width:1.8;fill:none;stroke-linecap:round;stroke-linejoin:round}.security-title{margin-top:18px;font-size:16px;font-weight:650}.security-copy{margin-top:7px;color:var(--muted);font-size:12px;line-height:1.62}.landing-footer{padding:28px 0 46px;border-top:1px solid var(--line-soft);display:flex;justify-content:space-between;gap:24px;color:var(--muted2);font-size:11px}
@media(max-width:900px){.landing-hero{grid-template-columns:1fr;gap:48px;padding:74px 0}.how-flow{grid-template-columns:1fr}.how-arrow{transform:rotate(90deg)}.how-grid{grid-template-columns:1fr}.setup-layout{grid-template-columns:1fr}.plugin-panel{position:relative;top:auto;grid-row:1}.security-grid{grid-template-columns:1fr}.landing-hero h1{font-size:clamp(46px,10vw,70px)}}
@media(max-width:600px){.landing-nav-inner,.landing-main{width:min(100% - 28px,1180px)}.landing-nav-inner{min-height:64px}.landing-links>a:first-child{display:none}.landing-hero{padding:58px 0 62px}.landing-hero h1{font-size:43px}.landing-hero-copy{font-size:15px}.connection-preview{padding:20px;border-radius:24px}.how-section{padding-bottom:62px}.how-shell{padding:20px;border-radius:22px}.usage-strip{flex-direction:column}.setup-section{padding:62px 0}.setup-step{grid-template-columns:1fr;padding:21px}.step-number{width:40px;height:40px;border-radius:12px}.plugin-panel{padding:20px}.plugin-spec{grid-template-columns:1fr;gap:4px}.landing-footer{flex-direction:column}}
`;

const brandHead = `<link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" type="image/png" href="/assets/codelocal-icon.png"><link rel="apple-touch-icon" href="/assets/apple-touch-icon.png"><meta name="theme-color" media="(prefers-color-scheme:light)" content="#f5f5f7"><meta name="theme-color" media="(prefers-color-scheme:dark)" content="#090a0d"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">`;

export const uiIcons = {
  folder: `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 7.5h6l2-2h9v13.5H3.5z"/><path d="M3.5 9.5h17"/></svg>`,
  folderCheck: `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 7.5h6l2-2h9v13.5H3.5z"/><path d="M3.5 9.5h17"/><path d="m8.5 14 2 2 4-4"/></svg>`,
} as const;

const navIcons = {
  overview: `<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>`,
  workspaces: `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 7.5h6l2-2h9v13.5H3.5z"/><path d="M3.5 9.5h17"/></svg>`,
  devices: `<svg viewBox="0 0 24 24" aria-hidden="true"><rect x="5" y="3" width="14" height="18" rx="3"/><path d="M9.5 6h5M11 18h2"/></svg>`,
  connect: `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M8 12h8M13 9l3 3-3 3"/><path d="M5 5.5h6M5 18.5h6"/></svg>`,
  security: `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v5c0 4.6-2.8 8.3-7 10-4.2-1.7-7-5.4-7-10V6z"/><path d="M9.5 12l1.7 1.7 3.5-4"/></svg>`,
} as const;

const dashboardScript = `
(() => {
  const dialog = document.getElementById('confirm-dialog');
  const title = document.getElementById('confirm-title');
  const copy = document.getElementById('confirm-copy');
  const confirm = document.getElementById('confirm-submit');
  let pendingForm = null;
  document.addEventListener('click', (event) => {
    const button = event.target.closest('[data-confirm]');
    if (!button || !dialog) return;
    event.preventDefault();
    pendingForm = button.closest('form');
    title.textContent = button.dataset.confirmTitle || 'Are you sure?';
    copy.textContent = button.dataset.confirmMessage || 'This action cannot be undone.';
    confirm.textContent = button.dataset.confirmLabel || 'Continue';
    confirm.className = 'btn ' + (button.dataset.confirmTone === 'danger' ? 'danger' : 'primary');
    dialog.showModal();
  });
  confirm?.addEventListener('click', () => {
    if (!pendingForm) return dialog?.close();
    const form = pendingForm;
    pendingForm = null;
    dialog?.close();
    form.requestSubmit();
  });
  document.querySelectorAll('[data-copy-target]').forEach((button) => {
    button.addEventListener('click', async () => {
      const target = document.querySelector(button.dataset.copyTarget);
      if (!target) return;
      const value = target.textContent || '';
      try {
        await navigator.clipboard.writeText(value.trim());
        const previous = button.textContent;
        button.textContent = 'Copied';
        setTimeout(() => button.textContent = previous, 1400);
      } catch {}
    });
  });
})();`;

const landingScript = `
document.querySelectorAll('[data-copy-value]').forEach((button) => {
  button.addEventListener('click', async () => {
    try {
      await navigator.clipboard.writeText(button.dataset.copyValue || '');
      const previous = button.textContent;
      button.textContent = 'Copied';
      setTimeout(() => button.textContent = previous, 1400);
    } catch {}
  });
});`;

export function landingPage(options: { endpoint: string; signedIn: boolean }) {
  const endpoint = escapeHtml(options.endpoint);
  let siteUrl = "https://codelocal.cloud";
  try { siteUrl = new URL(options.endpoint).origin; } catch {}
  const canonicalUrl = `${siteUrl}/`;
  const socialTitle = "CodeLocal — Let ChatGPT Code on Your Machine";
  const socialDescription = "Use ChatGPT as the AI brain for your local code. No separate OpenAI API key or per-token billing from CodeLocal.";
  const socialImage = `${siteUrl}/assets/codelocal-icon.png`;
  const accountAction = options.signedIn
    ? `<a class="btn primary" href="/dashboard">Open dashboard</a>`
    : `<a class="btn" href="/login">Sign in</a><a class="btn primary" href="/register">Create account</a>`;
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark">${brandHead}<title>${escapeHtml(socialTitle)}</title><meta name="description" content="${escapeHtml(socialDescription)}"><link rel="canonical" href="${escapeHtml(canonicalUrl)}"><meta property="og:type" content="website"><meta property="og:site_name" content="CodeLocal"><meta property="og:url" content="${escapeHtml(canonicalUrl)}"><meta property="og:title" content="${escapeHtml(socialTitle)}"><meta property="og:description" content="${escapeHtml(socialDescription)}"><meta property="og:image" content="${escapeHtml(socialImage)}"><meta property="og:image:secure_url" content="${escapeHtml(socialImage)}"><meta property="og:image:type" content="image/png"><meta property="og:image:alt" content="CodeLocal"><meta name="twitter:card" content="summary"><meta name="twitter:title" content="${escapeHtml(socialTitle)}"><meta name="twitter:description" content="${escapeHtml(socialDescription)}"><meta name="twitter:image" content="${escapeHtml(socialImage)}"><style>${styles}${premiumStyles}${landingStyles}</style></head><body><div class="landing">
  <nav class="landing-nav"><div class="landing-nav-inner"><a class="landing-brand" href="/"><img class="landing-logo" src="/assets/codelocal-icon.png" alt="CodeLocal"><span>CodeLocal</span></a><div class="landing-links"><a class="btn ghost" href="#setup">Setup guide</a>${accountAction}</div></div></nav>
  <main class="landing-main">
    <section class="landing-hero"><div><div class="landing-kicker"><span class="status-dot green"></span>CodeLocal Cloud</div><h1>You already have ChatGPT. Now let it code on your machine.</h1><div class="landing-hero-copy">ChatGPT stays the AI brain. CodeLocal gives it a secure MCP bridge to the project folders, terminal and Git tools you explicitly authorize on your computer.</div><div class="landing-actions"><a class="btn primary" href="#setup">Set up CodeLocal</a>${options.signedIn ? `<a class="btn" href="/dashboard/connect">Connection settings</a>` : `<a class="btn" href="/register">Create free account</a>`}</div><div class="privacy-note"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3l7 3v5c0 4.6-2.8 8.3-7 10-4.2-1.7-7-5.4-7-10V6z"/><path d="M9.5 12l1.7 1.7 3.5-4"/></svg>No separate OpenAI API key. No per-token billing from CodeLocal.</div></div><div class="connection-preview"><div class="preview-head"><img class="preview-icon" src="/assets/chatgpt-plugin-icon.png" alt="CodeLocal plugin icon"><div><div class="preview-title">CodeLocal</div><div class="preview-sub">Custom MCP plugin for ChatGPT</div></div></div><div class="preview-field"><div class="preview-label">Server URL</div><div class="preview-value">${endpoint}</div></div><div class="preview-row"><span>AI brain</span><strong>Your ChatGPT</strong></div><div class="preview-row"><span>Transport</span><strong>Remote MCP</strong></div><div class="preview-row"><span>CodeLocal token billing</span><strong>None</strong></div></div></section>
    <section class="how-section"><div class="section-kicker">How it works</div><h2 class="section-title">ChatGPT does the thinking. CodeLocal gives it hands.</h2><div class="section-copy">CodeLocal does not replace ChatGPT with another model. It connects the ChatGPT conversation you already use to carefully scoped tools on your own computer.</div><div class="how-shell"><div class="how-flow"><div class="how-node">You</div><div class="how-arrow">→</div><div class="how-node">ChatGPT</div><div class="how-arrow">→</div><div class="how-node">MCP</div><div class="how-arrow">→</div><div class="how-node">CodeLocal</div><div class="how-arrow">→</div><div class="how-node">Your computer</div></div><div class="how-grid"><div class="how-card"><div class="how-card-title">ChatGPT is the brain</div><div class="how-card-copy">Reasoning, planning and conversation use the model available in your ChatGPT account. You do not need to paste an OpenAI API key into CodeLocal.</div></div><div class="how-card"><div class="how-card-title">CodeLocal is the bridge</div><div class="how-card-copy">MCP tool calls are routed to the exact workspace you select, including file, Git and terminal tools. Source code and secrets remain on your machine.</div></div><div class="how-card"><div class="how-card-title">No CodeLocal token meter</div><div class="how-card-copy">CodeLocal does not charge you per AI input/output token. You keep using your existing ChatGPT plan while CodeLocal provides the local tool connection.</div></div></div><div class="usage-strip"><span class="usage-badge">Usage</span><div><strong>No separate MCP call quota from CodeLocal.</strong> Tool calls happen inside your ChatGPT conversation and follow the normal usage limits of your ChatGPT plan, model and workspace.</div></div></div></section>
    <section class="setup-section" id="setup"><div class="section-kicker">Detailed setup</div><h2 class="section-title">Set up CodeLocal in five steps.</h2><div class="section-copy">Connect ChatGPT, install CodeLocal, authorize only the project folders you want, then start the single machine runtime. Pairing happens automatically on the first runtime start.</div><div class="setup-layout"><div class="setup-list">
      <article class="setup-step"><div class="step-number">1</div><div><div class="step-title">Connect CodeLocal with ChatGPT</div><div class="step-summary">Create a custom plugin using the remote CodeLocal MCP endpoint.</div><ol class="step-details"><li>Open <strong>ChatGPT</strong>, choose <strong>Plugins</strong> in the left sidebar, then press the <strong>+</strong> button.</li><li>Choose <strong>New Plugin</strong> and upload the CodeLocal icon shown on this page.</li><li>Enter <strong>CodeLocal</strong> for the name and <strong>Connect ChatGPT to project folders you authorize on your computer.</strong> for the description.</li><li>Keep <strong>Server URL</strong> selected and enter <strong>${endpoint}</strong>.</li><li>Set <strong>Authentication</strong> to <strong>OAuth</strong>. Leave Advanced OAuth settings on the automatically discovered values.</li><li>Read the custom MCP risk notice, tick <strong>I understand and want to continue</strong>, then save the plugin.</li><li>When the browser opens, sign in or create your CodeLocal account and approve the OAuth connection. ChatGPT will return to the plugin after approval.</li></ol><div class="step-note"><strong>Can’t see Plugins?</strong> Plugin availability can depend on your ChatGPT plan, workspace and administrator settings.</div></div></article>
      <article class="setup-step"><div class="step-number">2</div><div><div class="step-title">Install CodeLocal on your computer</div><div class="step-summary">Node.js 20 or later and npm are required.</div><div class="code-block step-code">npm install -g codelocal@beta</div><div class="step-note"><strong>If npm reports EEXIST:</strong> run <code>npm uninstall -g codelocal</code>, then run the install command again. Avoid <code>--force</code> unless you have verified the conflicting file.</div></div></article>
      <article class="setup-step"><div class="step-number">3</div><div><div class="step-title">Authorize a project folder</div><div class="step-summary">Choose exactly which local project ChatGPT may use. This is a local-only action and does not connect to CodeLocal Cloud.</div><div class="code-block step-code">cd /absolute/path/to/your-project
codelocal .</div><div class="step-note">Repeat <code>codelocal .</code> inside any additional project you want to authorize. You can also use <code>codelocal grant /absolute/path/to/project</code>.</div></div></article>
      <article class="setup-step"><div class="step-number">4</div><div><div class="step-title">Start the machine runtime</div><div class="step-summary">Run one CodeLocal runtime for this computer. It syncs your authorized workspace list and waits for ChatGPT.</div><div class="code-block step-code">codelocal</div><ol class="step-details"><li>On the first start, your browser opens the CodeLocal approval page automatically.</li><li>Sign in with the same account used for the ChatGPT plugin and approve this computer.</li><li>Return to the terminal. The runtime stays running and connects to CodeLocal Cloud.</li><li>If another terminal runs <code>codelocal</code>, it reuses the existing machine runtime instead of starting a duplicate.</li></ol></div></article>
      <article class="setup-step"><div class="step-number">5</div><div><div class="step-title">Start working from ChatGPT</div><div class="step-summary">Select an authorized workspace in chat. Sleeping projects activate only when ChatGPT actually uses them.</div><ol class="step-details"><li>Return to ChatGPT and enable the <strong>CodeLocal</strong> plugin for the conversation.</li><li>Ask: <strong>“Use CodeLocal to list my authorized workspaces.”</strong></li><li>Choose the project you want. Multiple ChatGPT threads can use different workspaces on the same machine runtime.</li><li>Approve sensitive terminal or file actions when CodeLocal asks. You can review devices, workspaces and security activity in the dashboard.</li></ol><div class="step-note">Verify local setup any time with <code>codelocal status</code>. Stop the runtime with <code>codelocal stop</code>.</div></div></article>
    </div><aside class="plugin-panel"><div class="plugin-panel-head"><img class="plugin-panel-icon" src="/assets/chatgpt-plugin-icon.png" alt=""><div><div class="plugin-panel-title">ChatGPT plugin icon</div><div class="plugin-panel-sub">Ready to upload in New Plugin</div></div></div><div class="plugin-specs"><div class="plugin-spec"><div class="plugin-spec-key">Format</div><div class="plugin-spec-value">PNG</div></div><div class="plugin-spec"><div class="plugin-spec-key">Dimensions</div><div class="plugin-spec-value">256 × 256 px</div></div><div class="plugin-spec"><div class="plugin-spec-key">File size</div><div class="plugin-spec-value">Under 10 KB</div></div><div class="plugin-spec"><div class="plugin-spec-key">Server URL</div><div class="plugin-spec-value">${endpoint}</div></div><div class="plugin-spec"><div class="plugin-spec-key">Authentication</div><div class="plugin-spec-value">OAuth</div></div></div><a class="btn primary" href="/assets/chatgpt-plugin-icon.png" download="codelocal-chatgpt-plugin-icon.png">Download plugin icon</a><button class="btn" type="button" data-copy-value="${endpoint}">Copy Server URL</button><div class="size-ok">Meets ChatGPT’s 10 KB upload limit</div></aside></div></section>
    <section class="security-section"><div class="section-kicker">Private by design</div><h2 class="section-title">Your machine stays in control.</h2><div class="security-grid"><div class="security-card"><div class="security-icon">${uiIcons.folderCheck}</div><div class="security-title">Explicit workspace access</div><div class="security-copy">Only folders you grant with CodeLocal appear in ChatGPT. Revoke a workspace without deleting its files.</div></div><div class="security-card"><div class="security-icon">✓</div><div class="security-title">Local risk confirmation</div><div class="security-copy">Potentially destructive terminal or filesystem actions require approval before they run on your computer.</div></div><div class="security-card"><div class="security-icon">◎</div><div class="security-title">Revocable devices</div><div class="security-copy">Review and revoke paired computers from your dashboard whenever a machine is lost or no longer trusted.</div></div></div></section>
    <footer class="landing-footer"><span>© ${new Date().getFullYear()} CodeLocal</span><span>Local source code and secrets remain on your computer.</span></footer>
  </main></div><script>${landingScript}</script></body></html>`;
}

export function authPage(options: { title: string; subtitle: string; body: string }) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark">${brandHead}<title>${escapeHtml(options.title)} · CodeLocal</title><style>${styles}${premiumStyles}</style></head><body><div class="auth-wrap"><div class="auth"><div class="brand"><img class="logo" src="/assets/codelocal-icon.png" alt=""><span class="brand-name">CodeLocal</span></div><div class="card glow"><h1>${escapeHtml(options.title)}</h1><p>${escapeHtml(options.subtitle)}</p>${options.body}</div></div></div></body></html>`;
}

export function dashboardPage(options: {
  title: string;
  eyebrow?: string;
  subtitle?: string;
  active: "overview" | "devices" | "workspaces" | "connect" | "security";
  email: string;
  csrf: string;
  body: string;
  actions?: string;
}) {
  const nav = [
    ["overview", "/dashboard", "⌂", "Overview"],
    ["workspaces", "/dashboard/workspaces", "◇", "Workspaces"],
    ["devices", "/dashboard/devices", "◉", "Devices"],
    ["connect", "/dashboard/connect", "↗", "Connect ChatGPT"],
    ["security", "/dashboard/security", "⌁", "Security"],
  ] as const;
  const initial = options.email.trim().slice(0, 1).toUpperCase() || "U";
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="color-scheme" content="light dark">${brandHead}<title>${escapeHtml(options.title)} · CodeLocal</title><style>${styles}${premiumStyles}</style></head><body><div class="shell"><aside class="sidebar"><div class="brand"><img class="logo" src="/assets/codelocal-icon.png" alt=""><span class="brand-name">CodeLocal</span><span class="brand-tag">CLOUD</span></div><div class="nav-label">Control plane</div><nav class="nav">${nav.map(([key, href, _icon, label]) => `<a class="${options.active === key ? "active" : ""}" href="${href}"><span class="nav-icon">${navIcons[key]}</span><span>${label}</span></a>`).join("")}</nav><div class="sidebar-spacer"></div><div class="sidebar-status"><div class="sidebar-status-title"><span class="status-dot green"></span>Cloud connected</div><div class="sidebar-status-copy">Local source code and secrets stay on your machine.</div></div><div class="sidebar-foot"><div class="avatar">${escapeHtml(initial)}</div><div class="account"><div class="account-email">${escapeHtml(options.email)}</div><div class="account-meta">CodeLocal account</div></div><form method="post" action="/logout"><input type="hidden" name="csrf" value="${escapeHtml(options.csrf)}"><button class="btn ghost small" type="submit">Sign out</button></form></div></aside><main class="main"><header class="top"><div class="top-copy"><div class="eyebrow"><span class="status-dot green"></span>${escapeHtml(options.eyebrow ?? "CodeLocal Cloud")}</div><div class="h1">${escapeHtml(options.title)}</div>${options.subtitle ? `<div class="sub">${escapeHtml(options.subtitle)}</div>` : ""}</div>${options.actions ? `<div class="top-actions">${options.actions}</div>` : ""}</header>${options.body}</main></div><dialog id="confirm-dialog"><div class="modal"><div class="modal-icon">!</div><div class="modal-title" id="confirm-title">Are you sure?</div><div class="modal-copy" id="confirm-copy">This action cannot be undone.</div><div class="modal-actions"><button class="btn" type="button" onclick="this.closest('dialog').close()">Cancel</button><button class="btn danger" id="confirm-submit" type="button">Continue</button></div></div></dialog><script>${dashboardScript}</script></body></html>`;
}
